# Generated by Django 6.1 on 2026-08-27 18:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.PositiveIntegerField(db_index=True, editable=False, unique=True, verbose_name='Customer Number')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('direccion_entrega', models.TextField(blank=True, default='')),
                ('instrucciones_entrega', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['customer_number'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True, verbose_name='Tracking ID')),
                ('tipo', models.CharField(choices=[('directa', 'Directa'), ('asistida', 'Asistida')], default='directa', max_length=20)),
                ('producto', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('revision', 'En revisión'), ('info_requerida', 'Información requerida'), ('confirmada', 'Confirmada'), ('pago_pendiente', 'Pago pendiente'), ('pago_recibido', 'Pago recibido'), ('preparando', 'Preparando envío'), ('transito', 'En tránsito'), ('cuba', 'Llegó a Cuba'), ('disponible', 'Disponible para entrega'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], db_index=True, default='recibida', max_length=30)),
                ('destinatario_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('destinatario_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('destinatario_direccion', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('notas_internas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('usuario', models.CharField(default='sistema', max_length=150)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.orden', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Nota de orden',
                'verbose_name_plural': 'Notas de órdenes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('recibida', 'Recibida'), ('revision', 'En revisión'), ('info_requerida', 'Información requerida'), ('confirmada', 'Confirmada'), ('pago_pendiente', 'Pago pendiente'), ('pago_recibido', 'Pago recibido'), ('preparando', 'Preparando envío'), ('transito', 'En tránsito'), ('cuba', 'Llegó a Cuba'), ('disponible', 'Disponible para entrega'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], max_length=30, null=True)),
                ('estado_nuevo', models.CharField(choices=[('recibida', 'Recibida'), ('revision', 'En revisión'), ('info_requerida', 'Información requerida'), ('confirmada', 'Confirmada'), ('pago_pendiente', 'Pago pendiente'), ('pago_recibido', 'Pago recibido'), ('preparando', 'Preparando envío'), ('transito', 'En tránsito'), ('cuba', 'Llegó a Cuba'), ('disponible', 'Disponible para entrega'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], max_length=30)),
                ('nota', models.TextField(blank=True, default='')),
                ('usuario', models.CharField(default='sistema', max_length=150)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.orden', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['fecha'],
            },
        ),
    ]
