# Generated by Django 6.1 on 2026-08-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_capturaorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximo_envio', models.DateTimeField(blank=True, null=True, verbose_name='Próxima salida programada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
