# Generated by Django 6.1 on 2026-09-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={},
        ),
        migrations.AddField(
            model_name='configuracion',
            name='precio_celular',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Precio celular'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='precio_laptop',
            field=models.DecimalField(decimal_places=2, default=75.0, max_digits=8, verbose_name='Precio laptop'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='precio_tablet',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=8, verbose_name='Precio iPad / Tablet'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tarifa_mas_50',
            field=models.DecimalField(decimal_places=2, default=4.99, max_digits=6, verbose_name='Tarifa paquetes mayores de 50 lb'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tarifa_menos_50',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=6, verbose_name='Tarifa paquetes menores de 50 lb'),
        ),
    ]
