# Generated by Django 6.1 on 2026-09-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuracion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuración'},
        ),
    ]
