# Generated by Django 6.1 on 2026-09-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notificaciones_push_activas',
            field=models.BooleanField(default=True, verbose_name='Notificaciones Push activas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notificar_nueva_orden',
            field=models.BooleanField(default=True, verbose_name='Notificar nueva orden'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notificar_nuevo_cliente',
            field=models.BooleanField(default=True, verbose_name='Notificar nuevo cliente'),
        ),
    ]
