# Generated by Django 6.1 on 2026-09-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_notificaciones_push_activas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='notificaciones_push_activas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='notificar_nueva_orden',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='notificar_nuevo_cliente',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='notificaciones_push_activas',
            field=models.BooleanField(default=True, verbose_name='Notificaciones Push activas'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='notificar_nueva_orden',
            field=models.BooleanField(default=True, verbose_name='Notificar nueva orden'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='notificar_nuevo_cliente',
            field=models.BooleanField(default=True, verbose_name='Notificar nuevo cliente'),
        ),
    ]
