# Generated by Django 6.1 on 2026-10-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('registro_cliente', 'Registro de cliente (al cliente)'), ('orden_creada_cliente', 'Orden creada (al cliente)'), ('orden_creada_admin', 'Orden creada (al administrador)'), ('estado_actualizado', 'Cambio de estado (al cliente)')], max_length=50, unique=True)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plantilla de correo',
                'verbose_name_plural': 'Plantillas de correo',
            },
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_admin',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo que recibe los avisos (administrador)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='email_remitente',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo desde el que se envían las notificaciones'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre_remitente',
            field=models.CharField(blank=True, default='KOCH ENVÍOS', max_length=100, verbose_name='Nombre del remitente'),
        ),
    ]
