# Generated by Django 6.1 on 2026-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plantillacorreo_configuracion_email_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_notificado',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
