# Generated by Django 6.1 on 2026-10-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orden_estado_notificado_orden_fecha_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('referencia', models.CharField(blank=True, default='', max_length=60)),
                ('estado', models.CharField(choices=[('pendiente', 'Enviando'), ('enviado', 'Enviado'), ('fallido', 'No se envió')], db_index=True, default='pendiente', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('resuelto', models.BooleanField(db_index=True, default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de correo',
                'verbose_name_plural': 'Registro de correos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='configuracion',
            name='contacto_direccion',
            field=models.TextField(blank=True, default='8417 N Armenia Ave, Apto 827\nTampa, Florida 33604-2691\nEstados Unidos', verbose_name='Dirección de recepción en Estados Unidos'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='contacto_email',
            field=models.EmailField(blank=True, default='kochenvios@gmail.com', max_length=254, verbose_name='Correo de contacto (página principal)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='contacto_telefono_cuba',
            field=models.CharField(blank=True, default='+53 59307450', max_length=40, verbose_name='Teléfono de Cuba'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='contacto_telefono_usa',
            field=models.CharField(blank=True, default='+1 (813) 255-6899', max_length=40, verbose_name='Teléfono de Estados Unidos'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='contacto_whatsapp',
            field=models.CharField(blank=True, default='+53 59307450', max_length=40, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tarifa_mixto',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=6, verbose_name='Tarifa paquetes mezclados (por lb)'),
        ),
    ]
